id = "fhirpath"
name = "FHIRPath"
description = "FHIRPath language support with LSP"
version = "0.1.0"
schema_version = 1
authors = ["OctoFHIR Team <funyloony@gmail.com>"]
repository = "https://github.com/octofhir/fhirpath-rs"

[language_servers.fhirpath-lsp]
name = "FHIRPath LSP"
language = "fhirpath"
