# Windows-specific configuration to avoid LNK1318 PDB errors
[target.x86_64-pc-windows-msvc]
# Completely disable debug info to avoid PDB issues on CI
rustflags = [
    "-C", "debuginfo=0",
    "-C", "strip=symbols",
    "-C", "link-arg=/DEBUG:NONE",
    "-C", "link-arg=/INCREMENTAL:NO"
]

[target.x86_64-pc-windows-gnu]
# Also handle GNU Windows target
rustflags = [
    "-C", "debuginfo=0",
    "-C", "strip=symbols"
]